spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: aws
logging:
  level:
    org.hibernate.SQL: debug # logger를 통한 하이버네이트 실행 SQL 남기기